// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_MyScene.cpp"
#include "EWIEGA46WW/moc_diagfin.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_pieces.cpp"
#include "EWIEGA46WW/moc_score.cpp"
